// Code generated by goctl. DO NOT EDIT.
package types

type AdminInfoReq struct {
	Id int64 `path:"id"`
}

type AdminInfo struct {
	Id   int64  `path:"id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type AdminInfoResp struct {
	Base
	Data AdminInfo `json:"data"`
}

type AdminInfoUpdateReq struct {
	Id int64 `json:"id"`
	AdminInfo
}

type AdminInfoUpdateResp struct {
	Base
}

type Base struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
